language: php
os: linux
dist: bionic

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: LARAVEL=5.8.* ORCHESTRA=3.8.*
    - php: 7.3
      env: LARAVEL=^6.0 ORCHESTRA=^4.0
    - php: 7.4
      env: LARAVEL=^6.0 ORCHESTRA=^4.0
    - php: 7.3
      env: LARAVEL=^7.0 ORCHESTRA=^5.0
    - php: 7.4
      env: LARAVEL=^7.0 ORCHESTRA=^5.0 COVERAGE=1

  allow_failures:
    - env: COVERAGE=1

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

before_script:
  - if [[ -v LARAVEL ]]; then composer require laravel/framework:$LARAVEL --no-update; fi
  - if [[ -v ORCHESTRA ]]; then composer require orchestra/testbench:$ORCHESTRA --no-update; fi
  - if [[ -v ORCHESTRA_DB ]]; then composer require orchestra/database:$ORCHESTRA --no-update; fi

  - travis_retry composer install --no-interaction --prefer-source
  - phpenv rehash
  - set +H

script:
  - composer analyse
  - if [[ $COVERAGE != '1' ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE = '1' ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_script:
  - if [[ $COVERAGE = '1' ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
